import React from "react";

const Page = () => {
  return (
    <div style={{
      fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
      margin: 0,
      padding: '2rem',
      background: '#121212',
      color: '#f0f0f0',
      minHeight: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center'
    }}>
      <h1 style={{ fontSize: '3rem', color: '#4caf50' }}>enclov-AI</h1>
      <p style={{
        fontSize: '1.3rem',
        maxWidth: '600px',
        lineHeight: 1.5,
        color: '#b0b0b0',
        marginBottom: '2rem'
      }}>
        Revolutionize your GitHub pull request workflow with AI-powered, automatic code reviews.  
        enclov-AI analyzes your diffs, spots issues, and delivers expert-level feedback — all within GitHub.
      </p>
      <a
        href="https://github.com/Web4application/enclov-AI"
        target="_blank"
        rel="noopener noreferrer"
        style={{
          display: 'inline-block',
          backgroundColor: '#4caf50',
          color: '#fff',
          padding: '0.8em 1.8em',
          borderRadius: '4px',
          fontWeight: 600,
          textDecoration: 'none',
          marginBottom: '2rem',
          transition: 'background-color 0.3s ease'
        }}
        onMouseOver={(e) => (e.target.style.backgroundColor = '#3a9d3a')}
        onMouseOut={(e) => (e.target.style.backgroundColor = '#4caf50')}
      >
        View on GitHub
      </a>

      <section style={{ marginBottom: '2rem' }}>
        <h2>Features</h2>
        <ul style={{
          listStyle: 'none',
          padding: 0,
          maxWidth: '400px',
          margin: '0 auto',
          textAlign: 'left'
        }}>
          <li>• AI-powered review comments generated by OpenAI GPT models</li>
          <li>• Seamless GitHub App integration via webhooks</li>
          <li>• Detailed feedback on code diffs and PRs</li>
          <li>• Built with FastAPI, Celery, and Redis for scalable performance</li>
          <li>• Easy to deploy with Docker and Docker Compose</li>
        </ul>
      </section>

      <section>
        <h2>Get Started</h2>
        <p>
          1. Install the enclov-AI GitHub App on your repository.<br />
          2. Configure webhook URL pointing to your FastAPI server.<br />
          3. Open or update pull requests — sit back and watch AI-powered reviews roll in.
        </p>
      </section>

      <footer style={{ marginTop: 'auto', fontSize: '0.9rem', color: '#666' }}>
        &copy; 2025 enclov-AI by Kubu Lee. Built with passion, code, and AI.
      </footer>
    </div>
  );
};

export default Page;
